# configs/config.yaml

# CONFIGURATION FILE

app:
  env: "dev" # dev, prod

server:
  port: 8080 # Port from which Master listens to REST requests

workers:
  addresses:
    - "localhost:50051"
    # todo add more workers

storage:
  type: "local" # "local" or "s3"
  base_path: "data/" # Directory for data
  # s3_bucket: "my-bucket" #
  # s3_region: "us-east-1" #

# Task Configuration
tasks:
  - name: "iris-classification"
    type: "classification" # deve coincidere con l'enum (o stringa convertibile)
    dataset_path: "data/iris.csv"
    target_column: "Species"
    hyperparameters:
      n_estimators: 10
      max_depth: 5
    # Dati di test per la verifica rapida (opzionale ma comodo)
    test_features: [5.0, 3.6, 1.4, 0.2]

  - name: "housing-regression"
    type: "regression"
    dataset_path: "data/housing.csv"
    target_column: "median_house_value"
    hyperparameters:
      n_estimators: 15
      max_depth: 10
    test_features: [-122.23, 37.88, 41.0, 880.0, 129.0, 322.0, 126.0, 8.3252]